version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.3-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install dbt --upgrade

      - run:
          name: "Run Tests - Snowflake"
          command: |
            . venv/bin/activate
            cd integration_tests
            export DBT_PROFILES_DIR=/home/circleci/project/integration_tests
            echo $DBT_PROFILES_DIR
            dbt deps
            dbt run-operation create_artifact_resources
            dbt seed --full-refresh
            dbt run-operation upload_dbt_artifacts --args '{filenames: [manifest, run_results]}'
            dbt run --full-refresh
            dbt run
            dbt run-operation upload_dbt_artifacts --args '{filenames: [manifest, run_results]}'
            dbt test
            dbt run-operation upload_dbt_artifacts --args '{filenames: [run_results]}'
            dbt source snapshot-freshness
            dbt run-operation upload_dbt_artifacts --args '{filenames: [sources]}'
            dbt docs generate
            dbt run-operation upload_dbt_artifacts --args '{filenames: [catalog]}'

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
